version: '3'

services:
  kwazar_bot:
    image: d2avids/kwazar_bot:latest
    env_file: .env
    restart: always
    volumes:
      - ./logs:/kwazar_bot/logs
      - ./kwazar_db.db:/kwazar_bot/kwazar_db.db
    environment:
      - ENV TZ="Europe/Moscow"
      - PYTHONUNBUFFERED=1
    command: ["python", "main.py"]
