version: '3.8'

services:
  kwazar_bot:
    image: kwazar_bot:latest
    env_file: .env
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/kwazar_bot/logs
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "main.py"]
