name: Kwazar Bot Deploy
on:
  push:
    branches:
      - main
jobs:
  build_and_run:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Compress repo for transfer
        run: tar -czf repo.tar.gz .
      - name: Copy compressed repo to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          source: "repo.tar.gz"
          target: "kwazar_bot/repo.tar.gz"
      - name: Extract repo on server and build Docker-container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd kwazar_bot
            tar -xzf repo.tar.gz
            rm repo.tar.gz
            sudo docker compose down
            sudo docker system prune -f
            sudo docker image prune -f
            sudo docker compose up --build